package com.cachenote.server.security;


import com.cachenote.server.common.responseWrapper.BaseResponseWrapper;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;

/**
 * Wrap the response generated by Spring Security,
 * because the filter runs before request reaches
 * controllers, the GlobalExceptionHandler doesn't
 * work.
 */

@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class FilterResponseWrapper<T> extends BaseResponseWrapper<T> {

    public FilterResponseWrapper(int statusCode, String message, T data) {
        super(statusCode, message, data);
    }

    public static <T> FilterResponseWrapper<T> Result(int statusCode, String message, T data) {
        return new FilterResponseWrapper<>(statusCode, message, data);
    }

}
