package com.cachenote.server.security;


import com.cachenote.server.common.ResponseWrapper.ReceptionWrapper;
import lombok.AllArgsConstructor;
import lombok.Data;

/**
 *
 * Wrap the response generated by Spring Security,
 * because the filter runs before request reaches
 * controllers, the GlobalExceptionHandler doesn't
 * work.
 */
@Data
@AllArgsConstructor
public class FilterResponseWrapper<T> {
    private String message;
    private T data;

    public static <T> FilterResponseWrapper<T> Result(String message, T data) {
        return new FilterResponseWrapper<>(message, data);
    }
}
